server:
  port: 8081
spring:
  profiles:
    active: dev
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: 2tvmbT4eu7JKYMQd5HSOK482hLemlmOC
            client-secret: eIDHo45C9YmIfZm0TSTrkTKFBIsVgJKJKtQNkCrtzOrfcGDQ2vJEeR-IhQcT-t58
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-leeonscoding.us.auth0.com/