-- liquibase formatted sql

-- changeset liquibase:1

create table address (
    contact_id bigint unique,
    created_at timestamp(6),
    id bigint generated by default as identity,
    updated_at timestamp(6),
    city varchar(255),
    created_by varchar(255),
    state varchar(255),
    street varchar(255),
    updated_by varchar(255),
    zip varchar(255),
    primary key (id)
)

create table app_user (
    id bigint generated by default as identity,
    email varchar(255) not null,
    name varchar(255),
    phone varchar(255),
    primary key (id)
)

create table contact (
    created_at timestamp(6),
    id bigint generated by default as identity,
    updated_at timestamp(6),
    contact_type varchar(255) not null check (contact_type in ('CUSTOMER','SELLER')),
    created_by varchar(255),
    email varchar(255) not null,
    name varchar(255) not null,
    phone varchar(255) not null,
    updated_by varchar(255),
    primary key (id)
)

create index fn_name
   on contact (name)

create index fn_phone
   on contact (phone)

create index fn_email
   on contact (email)

alter table if exists address
   add constraint FK_CONTACT_ADDRESS
   foreign key (contact_id)
   references contact